{
 "title": "sbl dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Measurements",
    "label": "Socket measurements",
    "query": "checks, data_received, data_sent, iteration_duration, iterations, vus, vus_max, ws_connecting, ws_msgs_received, ws_msgs_sent, ws_session_duration, ws_sessions"
   }
  ]
 },
 "panels": [
  {
   "title": "check 200 by sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT sum(\"value\") FROM \"Measurement\" WHERE $timeFilter GROUP BY time($__interval), \"check\" fill(none)"
    }
   ]
  },
  {
   "title": "ws_connecting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"ws_connecting\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT min(\"value\") FROM \"ws_connecting\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT median(\"value\") FROM \"ws_connecting\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT max(\"value\") FROM \"ws_connecting\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT percentile(\"value\", 95) FROM \"ws_connecting\" WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)"
    },
    {
     "query": "SELECT percentile(\"value\", 90) FROM \"ws_connecting\" WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "VU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VUs Interval 2s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "vus",
     "query": "SELECT count(\"value\") FROM \"vus\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT percentile(\"value\", 95) FROM ws_sessions WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 16 },
   "targets": [
    {
     "query": "SELECT percentile(\"value\", 95) FROM ws_connecting WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "SELECT percentile(\"value\", 95) FROM data_sent WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "SELECT percentile(\"value\", 95) FROM data_received WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)"
    }
   ]
  }
 ]
}